from __future__ import annotations
import json
from pathlib import Path
from html import escape
ROOT = Path(__file__).resolve().parents[1]
items = [
{"id":"bf-027","slug":"sable-skin-studio","name":"Sable Skin Studio","industry":"beauty-personal-care","category":"Beauty & Personal Care","tags":["skincare","facials","esthetician","booking"],"description":"A polished esthetics experience for facials, skin programs, consultation, proof, and booking conversion.","bg":"#f3ebe6","fg":"#2a211f","accent":"#9c6d5a","soft":"#fffaf7","kicker":"SKINCARE WITH A POINT OF VIEW","headline":"Clinical care. Editorial calm. Skin-first confidence.","lede":"A premium esthetics experience built around consultation, treatment clarity, visible expertise, and an appointment path that feels considered rather than clinical.","cta":"Book a skin consultation","metrics":[["Custom","skin plans"],["60 min","signature facial"],["4.9★","client confidence"]],"sections":["Skin Consultation","Signature Facials","Corrective Programs"],"proof":"Treatment goals, practitioner credibility, and aftercare expectations are made clear before the visitor books.","layout":"editorial","reverse":False,"image":"https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-028","slug":"vertex-cyber-partners","name":"Vertex Cyber Partners","industry":"technology","category":"Technology","tags":["cybersecurity","msp","risk","technology"],"description":"A security-led technology site for managed defense, risk reduction, incident readiness, and executive consultation.","bg":"#08131d","fg":"#f4f7fa","accent":"#59c4d8","soft":"#102332","kicker":"CYBERSECURITY FOR OPERATING BUSINESSES","headline":"Reduce exposure before it becomes interruption.","lede":"A modern cyber advisory experience that translates security posture, response readiness, and managed protection into language executives can act on.","cta":"Request a security review","metrics":[["24/7","monitoring"],["<15 min","triage target"],["Board-ready","risk reporting"]],"sections":["Managed Defense","Risk & Compliance","Incident Readiness"],"proof":"Visitors see the operational outcomes, response model, and credibility signals before being asked to schedule a security conversation.","layout":"immersive","reverse":True,"image":"https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-029","slug":"sterling-family-law","name":"Sterling Family Law","industry":"professional-services","category":"Professional Services","tags":["family law","legal","divorce","consultation"],"description":"A composed family-law experience centered on discretion, process clarity, attorney authority, and consultation conversion.","bg":"#f5f1ea","fg":"#25221f","accent":"#8a6a45","soft":"#ffffff","kicker":"CLEAR COUNSEL FOR PERSONAL MATTERS","headline":"Steady guidance when the decisions are deeply personal.","lede":"A discreet legal experience built to explain process, reduce uncertainty, establish attorney authority, and move qualified visitors toward a private consultation.","cta":"Request a private consultation","metrics":[["Private","case intake"],["Clear","next steps"],["Focused","family counsel"]],"sections":["Divorce & Separation","Custody & Parenting","Agreements & Mediation"],"proof":"The site answers the emotional and practical questions prospects carry before presenting a calm, direct consultation path.","layout":"editorial","reverse":False,"image":"https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-030","slug":"meridian-concierge-medicine","name":"Meridian Concierge Medicine","industry":"health-family","category":"Health & Family","tags":["concierge medicine","primary care","wellness","membership"],"description":"A relationship-first concierge medicine experience for access, prevention, physician credibility, and membership inquiry.","bg":"#edf3f2","fg":"#17302f","accent":"#5d8e87","soft":"#ffffff","kicker":"PRIMARY CARE WITH TIME BUILT IN","headline":"A more personal relationship with your physician.","lede":"A refined concierge medicine experience centered on access, prevention, continuity, and the trust required for a high-value membership decision.","cta":"Explore membership","metrics":[["Same-week","access"],["Longer","visits"],["Preventive","care planning"]],"sections":["Membership Care","Preventive Planning","Direct Physician Access"],"proof":"Membership value, physician approach, and care boundaries are explained clearly before the inquiry form.","layout":"split","reverse":True,"image":"https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-031","slug":"skytable-aviation-catering","name":"Skytable Aviation Catering","industry":"aviation","category":"Aviation","tags":["aviation catering","private jet","fbo","hospitality"],"description":"A flight-aware aviation catering experience for curated menus, dietary precision, timing, and FBO delivery.","bg":"#f1eee8","fg":"#20262b","accent":"#aa7a43","soft":"#fffdf9","kicker":"CABIN DINING, TIMED TO THE FLIGHT","headline":"Private aviation catering without the last-minute uncertainty.","lede":"A high-touch catering experience built around wheels-up timing, dietary precision, elegant presentation, and delivery coordination with crews and FBOs.","cta":"Plan a flight order","metrics":[["Flight-time","coordination"],["Dietary","precision"],["FBO-ready","delivery"]],"sections":["Curated Menus","Crew & Passenger Needs","Flight Delivery"],"proof":"Menus, timing, packaging, and special-request handling are surfaced before the order inquiry so crews know exactly what to expect.","layout":"immersive","reverse":False,"image":"https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-032","slug":"runway-club-aviation-society","name":"Runway Club Aviation Society","industry":"aviation","category":"Aviation","tags":["aviation club","membership","pilots","events"],"description":"A member-led aviation society experience for events, access, community, benefits, and qualification-led applications.","bg":"#101820","fg":"#f5f0e6","accent":"#c3a46d","soft":"#19242d","kicker":"FOR PEOPLE WHO LIVE CLOSE TO AVIATION","headline":"A private society built around flight, access, and shared ambition.","lede":"An editorial membership experience combining aviation culture, member programming, private events, and a deliberate application path.","cta":"Apply for membership","metrics":[["Private","member events"],["Curated","aviation access"],["Global","member network"]],"sections":["Member Experiences","Flight & Field Events","Private Network"],"proof":"The club communicates belonging, exclusivity, and actual member value before asking a prospect to apply.","layout":"editorial","reverse":True,"image":"https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-033","slug":"azure-cay-villa-estates","name":"Azure Cay Villa Estates","industry":"real-estate-stays","category":"Real Estate & Stays","tags":["villas","luxury stays","property","concierge"],"description":"A destination-led villa estates experience for property discovery, concierge service, private stays, and direct inquiry.","bg":"#eef5f3","fg":"#19322f","accent":"#4f8e83","soft":"#ffffff","kicker":"ISLAND ESTATES, PRIVATELY CURATED","headline":"Stay somewhere that feels considered before you arrive.","lede":"A luxury villa experience focused on architecture, privacy, concierge planning, and the emotional pull of a destination rather than marketplace clutter.","cta":"Plan a private stay","metrics":[["Curated","villa estates"],["Private","guest planning"],["Concierge","arrival support"]],"sections":["Signature Estates","Island Experiences","Concierge Planning"],"proof":"Property fit, service detail, and destination mood are established before the guest is asked to inquire.","layout":"immersive","reverse":False,"image":"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-034","slug":"mariners-house-yacht-club","name":"Mariners House Yacht Club","industry":"marine","category":"Marine","tags":["yacht club","marina","membership","marine"],"description":"A heritage-modern yacht club experience for membership, marina life, events, dining, and private applications.","bg":"#e9eef0","fg":"#102734","accent":"#b28b58","soft":"#ffffff","kicker":"HARBOR LIFE, WITH A SENSE OF PLACE","headline":"A modern yacht club grounded in water, community, and tradition.","lede":"A premium marine membership experience combining berthing, social programming, dining, events, and a considered application journey.","cta":"Explore club membership","metrics":[["Marina","member access"],["Year-round","programming"],["Private","club events"]],"sections":["Marina & Berthing","Dining & Social","Member Calendar"],"proof":"Facilities, culture, programming, and membership expectations are presented together so prospects understand the life they are joining.","layout":"editorial","reverse":True,"image":"https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=1800&q=88"},
{"id":"bf-035","slug":"aurelia-med-spa","name":"Aurelia Med Spa","industry":"beauty-personal-care","category":"Beauty & Personal Care","tags":["med spa","aesthetics","injectables","skincare"],"description":"A premium medical aesthetics experience balancing treatment confidence, provider authority, results education, and consultation conversion.","bg":"#f3eee8","fg":"#302725","accent":"#a97868","soft":"#fffaf6","kicker":"AESTHETICS, REFINED AROUND YOU","headline":"Subtle results. Clinical confidence. A calmer kind of luxury.","lede":"A medical aesthetics experience designed to make treatment options, practitioner expertise, and consultation expectations feel clear, credible, and elevated.","cta":"Book an aesthetics consultation","metrics":[["Provider-led","treatment plans"],["Natural","result focus"],["Consult-first","experience"]],"sections":["Injectables","Skin Renewal","Body & Wellness"],"proof":"Provider qualifications, treatment philosophy, and realistic next steps are communicated before the visitor requests a consultation.","layout":"split","reverse":False,"image":"https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1800&q=88"}
]

def demo_html(x):
    cfg={k:x[k] for k in ["name","category","bg","fg","accent","soft","kicker","headline","lede","cta","metrics","sections","proof","layout","reverse"]}; cfg["visual"]=x["industry"]; cfg["heroImage"]=x["image"]
    desc=escape(x["description"], quote=True); slug=x["slug"]; name=escape(x["name"])
    return f'<!doctype html><html lang="en" data-brioframe-demo="true"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{desc}"><link rel="canonical" href="https://brioframe.github.io/demos/{slug}/"><meta property="og:title" content="{name} | BRIOFRAME Premium Preview"><meta property="og:description" content="{desc}"><meta property="og:type" content="website"><meta property="og:url" content="https://brioframe.github.io/demos/{slug}/"><title>{name} | BRIOFRAME Premium Preview</title><link rel="icon" href="/assets/brand/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/css/fonts.css"><link rel="stylesheet" href="/assets/css/demo-runtime.css"><script type="application/json" data-demo-config>{json.dumps(cfg,separators=(",",":"))}</script><script src="/assets/js/demo-runtime.js" defer></script></head><body><a class="skip-link" href="#main-content">Skip to demo content</a><main class="runtime-fallback" id="main-content"><a href="/">Return to Template Library</a><h1>{name}</h1><p>Premium Preview · {escape(x["category"])}</p><p>Simulated demo — this public form does not transmit or store data.</p><form data-demo-form><input aria-label="Demo field"></form></main></body></html>'
def preview_svg(x):
    slug=x["slug"]; title=escape(x["name"]); cat=escape(x["category"]); img=x["image"].replace("&","&amp;")
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 750" role="img" aria-labelledby="title desc" data-premium-preview="true"><title id="title">{title} premium website preview</title><desc id="desc">Responsive desktop and mobile presentation for {cat}.</desc><defs><clipPath id="screen"><rect x="410" y="144" width="610" height="390" rx="16"/></clipPath><clipPath id="phone"><rect x="925" y="290" width="150" height="292" rx="22"/></clipPath></defs><rect width="1200" height="750" fill="{x["bg"]}"/><circle cx="1080" cy="85" r="215" fill="{x["soft"]}"/><text x="70" y="92" fill="{x["accent"]}" font-family="Arial" font-size="20" font-weight="700" letter-spacing="4">{title.upper()}</text><text x="70" y="190" fill="{x["fg"]}" font-family="Georgia" font-size="56">{escape(x["headline"][:34])}</text><text x="72" y="260" fill="{x["accent"]}" font-family="Arial" font-size="18">{cat}</text><g data-device-frame="laptop"><rect x="380" y="115" width="668" height="452" rx="28" fill="#16191c"/><rect x="410" y="144" width="610" height="390" rx="16" fill="#fff"/><image href="{img}" x="410" y="144" width="610" height="390" preserveAspectRatio="xMidYMid slice" clip-path="url(#screen)"/><rect x="350" y="563" width="730" height="20" rx="10" fill="#b7b8b8"/></g><g data-device-frame="phone"><rect x="905" y="268" width="190" height="336" rx="34" fill="#16191c"/><rect x="925" y="290" width="150" height="292" rx="22" fill="#fff"/><image href="{img}" x="925" y="290" width="150" height="292" preserveAspectRatio="xMidYMid slice" clip-path="url(#phone)"/></g><rect x="70" y="390" width="260" height="58" rx="4" fill="{x["fg"]}"/><text x="96" y="426" fill="{x["soft"]}" font-family="Arial" font-size="16" font-weight="700">PREMIUM PREVIEW</text><text x="72" y="690" fill="{x["accent"]}" font-family="Arial" font-size="16" letter-spacing="3">BRIOFRAME TEMPLATE STUDIO</text></svg>'

catalog_path=ROOT/"data"/"templates.json"
catalog=json.loads(catalog_path.read_text(encoding="utf-8")); existing={r["slug"] for r in catalog}
for x in items:
    d=ROOT/"demos"/x["slug"]; d.mkdir(parents=True,exist_ok=True); (d/"index.html").write_text(demo_html(x),encoding="utf-8")
    (ROOT/"assets"/"previews"/f'{x["slug"]}.svg').write_text(preview_svg(x),encoding="utf-8")
    if x["slug"] not in existing:
        catalog.append({k:x[k] for k in ["id","slug","name","industry","category","tags","description"]}|{"previewImage":f'/assets/previews/{x["slug"]}.svg',"demoUrl":f'/demos/{x["slug"]}/',"shopifyProductUrl":"","availability":"Preview"})
catalog_path.write_text("[\n" + ",\n".join(json.dumps(record,ensure_ascii=False,separators=(",",":")) for record in catalog) + "\n]\n",encoding="utf-8")
print(f"Phase 4 build wrote {len(items)} premium previews; catalog={len(catalog)}")
